[[promises-overview]]
== Promise Overview

Not so many APIs are defined in <<es6-promises,ES6 Promises>> specification.

They can be categolized for following 3:

*Constructor*

Like `XMLHttpRequest`, you create promise object (instance) by the constructor function `Promise`.

You can create promise object by instanciating `Promise` constructor by `new`.

[source,javascript]
----
var promise = new Promise(function(resolve, reject) {
    // Asynchronous process
    // After the process finished, call resolve or reject
});
----

*Instance Method*

promise object has an instance method named `promise.then()` to register a callback function which is called when the promise is *resolve*d (success) or *reject*ed (failure)

[source,javascript]
----
promise.then(onFulfilled, onRejected)
----

When resolved (success)::
    `onFulfilled` is called
When rejected (failure)::
    `onRejected` is called

Both `onFulfilled`、`onRejected` are optional arguments.

You can register functions both on success and on failure in `promise.then`.
If you only write error process, you can use `promise.catch(onRejected)` which is same as `promise.then(undefined, onRejected)`.

[source,javascript]
promise.catch(onRejected)


*Static Method*

Global object `Promise` has some static methods.

For example, `Promise.all()` and `Promise.resolve()`. Most of them are supportive methods when you use Promise.


=== Promise workflow

Let's consider about following example.

[role="executable"]
[source,javascript]
[[promise-workflow.js]]
.promise-workflow.js
----
include::embed/embed-promise-workflow.js[]
----
<1> Promiseコンストラクタを `new` して、promiseオブジェクトを返します
<2> <1>のpromiseオブジェクトに対して `.then` で値が返ってきた時のコールバックを設定します

`asyncFunction` という関数 は promiseオブジェクトを返していて、
そのpromiseオブジェクトに対して `then` でresolveした時のコールバックを、
`catch` でエラーとなった場合のコールバックを設定しています。

このpromiseオブジェクトはsetTimeoutで16ms後にresolveされるので、
そのタイミングで `then` のコールバックが呼ばれ `'Async Hello world'` と出力されます。

この場合 `catch` のコールバックは呼ばれる事はないですが、
`setTimeout` が存在しない環境などでは、例外が発生し `catch` で登録したコールバック関数が呼ばれると思います。

もちろん、`promise.then(onFulfilled, onRejected)` というように、
`catch` を使わずに `then` を使い、以下のように2つのコールバック関数を設定することでもほぼ同様の動作になります。

[source,javascript]
----
asyncFunction().then(function (value) {
    console.log(value);
}, function (error) {
    console.log(error);
});
----

=== Promiseの状態 [[promise-states]]

Promiseの処理の流れが少しわかった所で、少しPromiseの状態について整理したいと思います。

`new Promise` でインスタンス化したpromiseオブジェクトには以下の3つの状態が存在します。

"has-resolution" - Fulfilled::
    resolve(成功)した時。この時 `onFulfilled` が呼ばれる
"has-rejection"  - Rejected::
    reject(失敗)した時。この時 `onRejected`  が呼ばれる
"unresolved" - Pending::
    resolveまたはrejectではない時。つまりpromiseオブジェクトが作成された初期状態等が該当する

読み方ですが、
左が<<es6-promises,ES6 Promises>>の仕様で定められている名前で、
右が<<promises-aplus, Promises/A+>>で登場する状態の名前になっています。

基本的にこの状態をプログラムで直接触る事はないため、名前自体は余り気にしなくても問題ないです。
この書籍では、 http://promises-aplus.github.io/promises-spec/[Promises/A+] の __Pending__、__Fulfilled__ 、__Rejected__
を用いて解説していきます。

.promise states
image::img/promise-states.png[promise-states]


[NOTE]
====
http://people.mozilla.org/~jorendorff/es6-draft.html#sec-promise-objects[ECMAScript Language Specification ECMA-262 6th Edition – DRAFT] では `+++[[PromiseStatus]]+++` という内部定義によって状態が定められています。
`+++[[PromiseStatus]]+++` にアクセスするユーザーAPIは用意されていないため、基本的には知る方法はありません。
====

3つの状態を見たところで、既にこの章で全ての状態が出てきていることが分かります。

promiseオブジェクトの状態は、一度__Pending__から__Fulfilled__や__Rejected__になると、
そのpromiseオブジェクトの状態はそれ以降変化することはなくなります。

つまり、PromiseはEvent等とは違い、`.then` で登録した関数が呼ばれるのは1回限りという事が明確になっています。

また、__Fulfilled__と__Rejected__のどちらかの状態であることを**Settled**(不変の)と表現することがあります。

Settled::
    resolve(成功) または reject(失敗) した時。

__Pending__と__Settled__が対となる関係であると考えると、Promiseの状態の種類/遷移がシンプルであることがわかると思います。

このpromiseオブジェクトの状態が変化した時に、一度だけ呼ばれる関数を登録するのが `.then` といったメソッドとなるわけです。

[NOTE]
====
https://speakerdeck.com/kerrick/javascript-promises-thinking-sync-in-an-async-world[JavaScript Promises - Thinking Sync in an Async World // Speaker Deck]
というスライドではPromiseの状態遷移について分かりやすく書かれています。
====

